The-Noisy-Rhinoceroses/BookingApp-Backend

app.js
=> fix(app.js): added underscore and removed empty line

app.js, package.json, routes/barbers.js
=> feat(routes): set up GET route for all barbers

app.js, routes/barbers.js, routes/index.js
=> feat(apiRoutes): code split api routes

bin/www
=> fix(port): Change port to 1337

db/appointments.js, db/customers.js
=> feat(appointments): make schema for appointments

package-lock.json, package.json, routes/appointments.js, routes/index.js
=> feat(appointment.js):User can retrieve apt

routes/barbers.js
=> feat(barbers): Create POST route for a new barber

routes/barbers.js
=> feat(barbers): Get one single barber

routes/appointments.js
=> feat(appointment): make delete route for appointments

routes/barbers.js
=> feat(barbers): Create delete route for single barber

routes/barbers.js
=> feat(barbers): Create put route for single barber

app.js, bin/www, routes/appointments.js, routes/barbers.js, routes/customers.js, routes/index.js, routes/users.js, utilities/utils.js
=> refactor(routes): standardize variable declarations

db/appointments.js, routes/appointments.js, routes/customers.js
=> feat(routes):User can create appointments

routes/appointments.js
=> fix(appointments): Replace barberId with actual id

db/appointments.js, routes/appointments.js
=> fix(appointments): Objectify barberId and CustomerId

routes/appointments.js, utilities/emails.js
=> chore(utilities/emails): include barber's full name in email

app.js, bin/config.js, bin/www, db/appointments.js, db/barbers.js, db/customers.js, routes/appointments.js, routes/barbers.js, routes/customers.js, routes/index.js, utilities/emails.js, utilities/queries.js
=> chore(general): refactor routers, split up www, and provide documentation

app.js, package-lock.json, package.json
=> Add helmet and compression #53

package-lock.json, routes/barbers.js
=> feat(routes): grab all appointments for selected barber

routes/barbers.js
=> feat(barbers): BarberId/Appointments only sends back date

package-lock.json, package.json, utilities/emails.js
=> Publish event to gmail #61

app.js, package-lock.json, package.json, routes/auth/index.js, routes/barbers.js, utilities/hashing.js
=> Authenticate barbers #63

routes/barbers.js
=> feat(appointments): Appointments now come with customer info

routes/index.js, routes/services.js
=> feat(services): Serve all services from DB

db/appointments.js, db/barbers.js, db/customers.js, db/services.js, utilities/seed.js
=> Update seed file to reflect schema #75

routes/barbers.js
=> feat(barbers): Serve up barber descriptions in relevant routes

routes/appointments.js
=> feat(appointments): Insert selectedServices into appointment document

db/appointments.js, db/services.js, utilities/seed.js
=> feat(seed): Add validations and dummy data to appointments

routes/appointments.js, utilities/adder.js
=> feat(adder.js): Calculate total duration and total price of appointment

db/reviews.js
=> feat(review): Add review Schema

utilities/seed.js
=> feat(seed): Add reviews to the seed file

routes/barbers.js
=> feat(reviews): Add Barber get and post review Routes

app.js
=> feat (app): Add secure and httpOnly options to cookies
